name: never_late_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_riverpod: ^2.0.6
  riverpod_annotation: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  patrol: ^3.17.0

flutter:
  uses-material-design: true

patrol:
  app_name: Never Late App
  android:
    package_name: com.example.never_late_app
  # ios:
  #   bundle_id: com.example.NeverLateApp
  # macos:
  #   bundle_id: com.example.macos.NeverLateApp